name: Verify XML

concurrency:
  group: verify-xml-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  verify:
    uses: actions/verify-xml-action@v2
    with:
      path: "./"
      file-endings: ".xml"
